spring.application.name=backend-java

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Security & Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT Secret
JWT_SECRET=generate_a_random_long_string_here_for_security

# Custom Portfolio Properties
admin.personal.email=${ADMIN_EMAIL}
portfolio.domain.link=${DOMAIN_LINK}

# Spring Mail Configuration (Gmail Example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SENDER_EMAIL}
spring.mail.password=${SENDER_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
